// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentGateway.Data;

namespace PaymentGateway.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class bankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PaymentGateway.Data.Card", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<string>("CardNumber")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<decimal?>("DayLimit")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("varchar(4)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal?>("TransactionLimit")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.ToTable("card");
                });

            modelBuilder.Entity("PaymentGateway.Data.Payment", b =>
                {
                    b.Property<byte?>("Accepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10,0)");

                    b.Property<string>("CardId")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<string>("Currency")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<DateTime?>("DateofTransaction")
                        .HasColumnType("datetime");

                    b.Property<string>("Id")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.ToTable("payment");
                });
#pragma warning restore 612, 618
        }
    }
}
